# Generated by Django 4.0.6 on 2022-11-28 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('geometry', models.CharField(default='Point', max_length=16)),
                ('alternative_id', models.IntegerField(blank=True, null=True)),
                ('content_online', models.BooleanField(default=False)),
                ('primary_city_name', models.CharField(blank=True, max_length=64, null=True)),
                ('alternative_city_names', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative city names')),
                ('primary_region_name', models.CharField(blank=True, max_length=64, null=True)),
                ('alternative_region_names', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative region names')),
                ('primary_country_name', models.CharField(blank=True, default='Ukraine', max_length=64, null=True)),
                ('alternative_country_names', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative country names')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('postcode', models.CharField(blank=True, max_length=256, null=True)),
                ('district', models.CharField(blank=True, max_length=256, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=256, null=True)),
                ('number_of_days_after_anchor_date_that_event_began', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_days_after_anchor_date_that_event_ended', models.IntegerField(blank=True, default=0, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='Title', max_length=64, null=True)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('marker_color', models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=16, null=True)),
                ('number_of_sites', models.IntegerField(blank=True, default=1, null=True)),
                ('number_of_casualties', models.CharField(blank=True, default='0', max_length=128, null=True)),
                ('number_of_memorials', models.IntegerField(blank=True, null=True)),
                ('type_of_place_before_event', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('occupation_period', models.CharField(blank=True, max_length=256, null=True)),
                ('map_event_followers', models.ManyToManyField(blank=True, default=None, related_name='map_event_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=64, unique=True)),
                ('description', models.TextField(default='Description')),
                ('map_image', models.FileField(blank=True, null=True, upload_to='maps/maps/images')),
                ('anchor_date', models.DateField(default='1939-09-01')),
                ('last_date', models.DateField(default='1945-05-01')),
                ('excel_upload', models.FileField(blank=True, null=True, upload_to='map_excel_files')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='maps/events/videos')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='maps/events/images')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='parent_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.map'),
        ),
    ]
