# Generated by Django 4.0.6 on 2022-08-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmeta',
            old_name='link',
            new_name='keyword',
        ),
    ]
