# Generated by Django 4.0.6 on 2022-11-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='last_date',
            field=models.DateField(default='1945-05-01'),
        ),
        migrations.AlterField(
            model_name='event',
            name='marker_color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='anchor_date',
            field=models.DateField(default='1939-09-01'),
        ),
    ]
