# Generated by Django 4.0.6 on 2022-08-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_link_mapmeta_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='MapGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('color', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=16)),
                ('map_group', models.ManyToManyField(blank=True, to='maps.mapgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MarkerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.marker')),
            ],
        ),
        migrations.DeleteModel(
            name='MapMeta',
        ),
    ]
