# Generated by Django 4.0.6 on 2022-11-14 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_map_last_date_alter_event_marker_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_event_followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='map_event_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
