# Generated by Django 4.0.6 on 2022-11-14 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0003_event_map_event_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='map_event_followers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='map_event_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
