# Generated by Django 4.0.6 on 2022-08-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_map_mapgroup_marker_markerlink_delete_mapmeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarkerLink',
        ),
    ]
