# Generated by Django 4.0.6 on 2022-11-14 13:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_event_map_event_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='primary_country_name',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
