# Generated by Django 4.0.6 on 2022-11-14 13:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_event_primary_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='primary_country_name',
            field=django_countries.fields.CountryField(default='UA', max_length=2),
        ),
    ]
