# Generated by Django 4.0.6 on 2022-09-21 15:03

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('maps', '0006_alternativeregionnames_event_anchor_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeCityNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlternativeCountryNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='alternative_region_names',
        ),
        migrations.AddField(
            model_name='event',
            name='alternative_country_names',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='maps.AlternativeCountryNames', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='alternative_city_names',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='maps.AlternativeCityNames', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='alternativecountrynames',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.event'),
        ),
        migrations.AddField(
            model_name='alternativecountrynames',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='alternativecitynames',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.event'),
        ),
        migrations.AddField(
            model_name='alternativecitynames',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
