# Generated by Django 4.0.6 on 2022-09-21 21:28

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('maps', '0007_alternativecitynames_alternativecountrynames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alternative_city_names',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='maps.AlternativeCityNames', to='taggit.Tag', verbose_name='Alternative city names'),
        ),
        migrations.AlterField(
            model_name='event',
            name='alternative_country_names',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='maps.AlternativeCountryNames', to='taggit.Tag', verbose_name='Alternative country names'),
        ),
        migrations.AlterField(
            model_name='event',
            name='alternative_region_names',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='maps.AlternativeRegionNames', to='taggit.Tag', verbose_name='Alternative region names'),
        ),
    ]
