# Generated by Django 4.0.6 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_alter_event_primary_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='primary_country_name',
            field=models.CharField(blank=True, default='Ukraine', max_length=64, null=True),
        ),
    ]
