# Generated by Django 4.0.6 on 2022-11-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_event_primary_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_place_before_event',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
