# Generated by Django 4.0.6 on 2022-09-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_alter_event_alternative_city_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='anchor_data',
            new_name='anchor_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
