# Generated by Django 4.0.6 on 2022-11-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0009_alter_event_type_of_place_before_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativecountrynames',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='alternativecountrynames',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='alternativeregionnames',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='alternativeregionnames',
            name='tag',
        ),
        migrations.AddField(
            model_name='map',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AlternativeCityNames',
        ),
        migrations.DeleteModel(
            name='AlternativeCountryNames',
        ),
        migrations.DeleteModel(
            name='AlternativeRegionNames',
        ),
    ]
