# Generated by Django 4.0.6 on 2022-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_eventdetails_remove_event_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='map_group',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Title', max_length=64),
        ),
        migrations.AddField(
            model_name='map',
            name='excel_upload',
            field=models.FileField(blank=True, null=True, upload_to='map_excel_files'),
        ),
        migrations.DeleteModel(
            name='MapGroup',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
