# Generated by Django 4.0.6 on 2022-11-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_eventvideo_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
