# Generated by Django 4.0.6 on 2022-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_eventimage_description_eventimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='maps/events/images'),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='maps/events/videos'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_image',
            field=models.FileField(blank=True, null=True, upload_to='maps/maps/images'),
        ),
    ]
