# Generated by Django 4.0.6 on 2022-10-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_remove_marker_map_group_event_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='excel_upload',
        ),
    ]
