# Generated by Django 4.0.6 on 2022-10-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_remove_map_excel_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='excel_upload',
            field=models.FileField(blank=True, null=True, upload_to='map_excel_files'),
        ),
    ]
