# Generated by Django 4.0.6 on 2022-10-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_map_excel_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetails',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='number_of_days_after_anchor_date_that_event_started',
            new_name='number_of_days_after_anchor_date_that_event_ended',
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_casualties',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_sub_sites',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
