# Generated by Django 4.0.6 on 2022-10-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_delete_eventdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_casualties',
            field=models.CharField(blank=True, default='0', max_length=128, null=True),
        ),
    ]
