# Generated by Django 4.0.6 on 2022-10-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_event_alternative_id_event_content_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='number_of_sub_sites',
            new_name='number_of_sites',
        ),
        migrations.RemoveField(
            model_name='event',
            name='anchor_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='color',
        ),
        migrations.RemoveField(
            model_name='map',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='marker_color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], default='blue', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_memorials',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='occupation_period',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_place_before_event',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='map',
            name='anchor_date',
            field=models.DateField(default='1945-09-01'),
        ),
    ]
