# Generated by Django 4.0.6 on 2022-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_rename_number_of_sub_sites_event_number_of_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(default='Title', max_length=64),
        ),
    ]
