# Generated by Django 4.0.6 on 2022-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_map_description_alter_map_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
