# Generated by Django 4.0.6 on 2022-10-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_alter_map_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_days_after_anchor_date_that_event_began',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_days_after_anchor_date_that_event_ended',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_memorials',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_place_before_event',
            field=models.CharField(blank=True, default='0', max_length=128, null=True),
        ),
    ]
