# Generated by Django 4.0.6 on 2022-10-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='alternative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
