# Generated by Django 4.0.6 on 2022-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_alter_event_alternative_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
