# Generated by Django 4.0.6 on 2022-10-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_event_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.map'),
        ),
    ]
