# Generated by Django 4.0.6 on 2022-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_alter_event_alternative_city_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hours',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
