# Generated by Django 4.0.6 on 2022-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_event_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(default='Title', max_length=64, unique=True),
        ),
    ]
