# Generated by Django 4.0.6 on 2022-10-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_alter_map_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='alternative_city_names',
        ),
        migrations.AddField(
            model_name='event',
            name='alternative_city_names',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative city names'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='alternative_country_names',
        ),
        migrations.AddField(
            model_name='event',
            name='alternative_country_names',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative country names'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='alternative_region_names',
        ),
        migrations.AddField(
            model_name='event',
            name='alternative_region_names',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative region names'),
        ),
    ]
