# Generated by Django 4.0.6 on 2022-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_remove_event_alternative_city_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image_url',
        ),
        migrations.AddField(
            model_name='map',
            name='map_image',
            field=models.FileField(blank=True, null=True, upload_to='map_images'),
        ),
    ]
