# Generated by Django 4.0.6 on 2022-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorsicanBibleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('corsican_stlc', models.CharField(max_length=100)),
                ('corsican_titre', models.CharField(max_length=100)),
                ('corsican_lines', models.TextField()),
                ('french_stlc', models.CharField(max_length=100)),
                ('french_titre', models.CharField(max_length=100)),
                ('french_lines', models.TextField()),
                ('page_url', models.CharField(default='http://projetbabel.org/bibbia_corsa/index.php', max_length=255)),
            ],
        ),
    ]
