# Generated by Django 4.0.6 on 2023-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='venmoHandle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ACCOUNT_BALANCE',
            field=models.FloatField(default=0.0),
        ),
    ]
