# Generated by Django 4.0.6 on 2022-09-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_primary_twitter_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='num_credits',
            new_name='credits',
        ),
    ]
