# Generated by Django 4.0.6 on 2023-02-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_alter_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(choices=[('Georgetown University', 'Georgetown University')], default='Georgetown University', max_length=64),
        ),
    ]
