# Generated by Django 4.0.6 on 2022-10-20 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_profile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=32, null=True)),
                ('hasBeenUsed', models.BooleanField(default=False)),
                ('generatedBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generatedBy', to=settings.AUTH_USER_MODEL)),
                ('usedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
