# Generated by Django 4.0.6 on 2023-02-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('notification_type', models.CharField(blank=True, choices=[('purchase', 'purchase'), ('sale', 'sale'), ('membership request', 'membership request'), ('membership accepted', 'membership accepted'), ('listing created', 'listing created'), ('listing deleted', 'listing deleted'), ('listing updated', 'listing updated'), ('payment request', 'payment request'), ('lottery winner', 'lottery winner')], max_length=64, null=True)),
            ],
        ),
    ]
