# Generated by Django 4.0.6 on 2022-10-20 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_profile_referral_code_referralcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='hasBeenUsed',
            new_name='usesMaximized',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='numberOfTimesUsed',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='usedBy',
        ),
        migrations.AddField(
            model_name='referralcode',
            name='usedBy',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='usedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
