# Generated by Django 4.0.6 on 2023-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_notified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('purchase', 'purchase'), ('sale', 'sale'), ('membership request', 'membership request'), ('membership accepted', 'membership accepted'), ('listing created', 'listing created'), ('listing updated', 'listing updated'), ('payment request', 'payment request'), ('lottery winner', 'lottery winner')], max_length=64, null=True),
        ),
    ]
