# Generated by Django 4.0.6 on 2022-10-20 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_rename_hasbeenused_referralcode_usesmaximized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='usedBy',
            field=models.ManyToManyField(blank=True, default=None, related_name='usedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
