# Generated by Django 4.0.6 on 2022-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_referralcode_usedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='numberOfTimesUsed',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='usesMaximized',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
