# Generated by Django 4.0.6 on 2023-03-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='institution',
        ),
    ]
