# Generated by Django 4.0.6 on 2022-10-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_referralcode_numberoftimesused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hasUsedReferralCode',
            field=models.BooleanField(default=False),
        ),
    ]
