# Generated by Django 4.0.6 on 2023-03-20 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='inserted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
