# Generated by Django 4.0.6 on 2022-10-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_hasusedreferralcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hasUsedReferralCode',
            new_name='hasUsedAReferralCode',
        ),
    ]
