# Generated by Django 4.0.6 on 2023-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification_inserted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='inserted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
