# Generated by Django 4.0.6 on 2022-10-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_hasusedreferralcode_profile_hasusedareferralcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verified_course_creator',
            new_name='verified_creator',
        ),
    ]
