# Generated by Django 4.0.6 on 2022-10-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='superuser',
            new_name='has_superuser_status',
        ),
    ]
