# Generated by Django 4.0.6 on 2022-10-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_superuser_profile_has_superuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_superuser_status',
            new_name='has_super_status',
        ),
    ]
