# Generated by Django 4.0.6 on 2022-10-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_has_superuser_status_profile_has_super_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='select_view_seen',
        ),
    ]
