# Generated by Django 4.0.6 on 2022-10-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_profile_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_requested', models.DateTimeField(auto_now_add=True)),
                ('user_receiving_follow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_follow_request', to=settings.AUTH_USER_MODEL)),
                ('user_requesting_to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_to_follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
