# Generated by Django 4.0.6 on 2022-10-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excel_upload',
            field=models.FileField(blank=True, null=True, upload_to='map_excel_files'),
        ),
    ]
