# Generated by Django 4.0.6 on 2022-10-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_excel_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='excel_upload',
        ),
    ]
