# Generated by Django 4.0.6 on 2022-10-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_profile_excel_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ACCOUNT_BALANCE',
            field=models.IntegerField(default=0),
        ),
    ]
