# Generated by Django 4.0.6 on 2022-11-11 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Assignment', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estimated_minutes_to_complete', models.FloatField(default=30)),
                ('language', models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('sq', 'Albanian'), ('am', 'Amharic'), ('ar', 'Arabic'), ('hy', 'Armenian'), ('az', 'Azerbaijani'), ('eu', 'Basque'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('bs', 'Bosnian'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('ceb', 'Cebuano'), ('ny', 'Chichewa'), ('zh-cn', 'Chinese Simplified'), ('zh-tw', 'Chinese Traditional'), ('co', 'Corsican'), ('hr', 'Croatian'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('eo', 'Esperanto'), ('et', 'Estonian'), ('tl', 'Filipino'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('gl', 'Galician'), ('ka', 'Georgian'), ('de', 'German'), ('el', 'Greek'), ('gu', 'Gujarati'), ('ht', 'Haitian Creole'), ('ha', 'Hausa'), ('haw', 'Hawaiian'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hmn', 'Hmong'), ('hu', 'Hungarian'), ('is', 'Icelandic'), ('ig', 'Igbo'), ('id', 'Indonesian'), ('ga', 'Irish'), ('it', 'Italian'), ('ja', 'Japanese'), ('jw', 'Javanese'), ('kn', 'Kannada'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('ko', 'Korean'), ('ku', 'Kurdish Kurmanji'), ('ky', 'Kyrgyz'), ('lo', 'Lao'), ('la', 'Latin'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('lb', 'Luxembourgish'), ('mk', 'Macedonian'), ('mg', 'Malagasy'), ('ms', 'Malay'), ('ml', 'Malayalam'), ('mt', 'Maltese'), ('mi', 'Maori'), ('mr', 'Marathi'), ('mn', 'Mongolian'), ('my', 'Myanmar Burmese'), ('ne', 'Nepali'), ('no', 'Norwegian'), ('or', 'Odia'), ('ps', 'Pashto'), ('fa', 'Persian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pa', 'Punjabi'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sm', 'Samoan'), ('gd', 'Scots Gaelic'), ('sr', 'Serbian'), ('st', 'Sesotho'), ('sn', 'Shona'), ('sd', 'Sindhi'), ('si', 'Sinhala'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('so', 'Somali'), ('es', 'Spanish'), ('su', 'Sundanese'), ('sw', 'Swahili'), ('sv', 'Swedish'), ('tg', 'Tajik'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('ug', 'Uyghur'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('cy', 'Welsh'), ('xh', 'Xhosa'), ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('zu', 'Zulu'), ('ee', 'Et')], default='en', max_length=64)),
                ('assignment_type', models.CharField(choices=[('Choose an assignment type', 'Choose an assignment type'), ('Text', 'Text'), ('Internal Link', 'Internal Link'), ('External Reading Link', 'External Reading Link'), ('External Link', 'External Link'), ('Iframe Link', 'Iframe Link'), ('Corsican Bible Chapter', 'Corsican Bible Chapter'), ('Youtube Video Link', 'Youtube Video Link'), ('Youtube Video Transcript ID', 'Youtube Video Transcript ID'), ('Article', 'Article')], default='Choose an assignment type', max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('internal_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('external_reading_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('external_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('iframe_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('youtube_video_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('youtube_video_transcript_id', models.CharField(blank=True, default='#', max_length=127, null=True)),
                ('article_by_url', models.BooleanField(blank=True, null=True)),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='assignment_completed', to=settings.AUTH_USER_MODEL)),
                ('corsican_bible_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corsican_bible_chapter_assignment', to='languages.corsicanbiblechapter')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Category', max_length=64, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('allowed_editors', models.ManyToManyField(blank=True, default=None, related_name='category_allowed_editors', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_category', to=settings.AUTH_USER_MODEL)),
                ('edit_access_request', models.ManyToManyField(blank=True, default=None, related_name='category_edit_access_request', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, default=None, related_name='category_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Course', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Mixed', 'Mixed'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult'), ('Advanced', 'Advanced')], default='Beginner', max_length=100)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('allowed_editors', models.ManyToManyField(blank=True, default=None, related_name='course_allowed_editors', to=settings.AUTH_USER_MODEL)),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='course_completed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_course', to=settings.AUTH_USER_MODEL)),
                ('edit_access_request', models.ManyToManyField(blank=True, default=None, related_name='course_edit_access_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Field', max_length=64, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('allowed_editors', models.ManyToManyField(blank=True, default=None, related_name='field_allowed_editors', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_of_field', to='ecoles.category')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_field', to=settings.AUTH_USER_MODEL)),
                ('edit_access_request', models.ManyToManyField(blank=True, default=None, related_name='field_edit_access_request', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, default=None, related_name='field_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Module', max_length=64)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='module_completed', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_within_course', to='ecoles.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Read', 'Read'), ('Watch', 'Watch'), ('Notes', 'Notes'), ('Write', 'Write')], default='Read', max_length=15)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_within_assignment', to='ecoles.assignment')),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='task_completed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Submodule', max_length=128)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='submodule_completed', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules_within_module', to='ecoles.module')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Specialization', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Mixed', 'Mixed'), ('Intermediate', 'Intermediate'), ('Difficult', 'Difficult'), ('Advanced', 'Advanced')], default='Beginner', max_length=100)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('allowed_editors', models.ManyToManyField(blank=True, default=None, related_name='specialization_allowed_editors', to=settings.AUTH_USER_MODEL)),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='specialization_completed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_specialization', to=settings.AUTH_USER_MODEL)),
                ('edit_access_request', models.ManyToManyField(blank=True, default=None, related_name='specialization_edit_access_request', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations_within_field', to='ecoles.field')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_specialization', to='auth.group')),
                ('purchasers', models.ManyToManyField(blank=True, default=None, related_name='specialization_purchasers', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, default=None, related_name='specialization_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_keyword', models.CharField(default='', max_length=16)),
                ('svg_url', models.CharField(default='', max_length=256)),
                ('students', models.ManyToManyField(blank=True, default=None, related_name='ecole_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_within_field', to='ecoles.field'),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_course', to='auth.group'),
        ),
        migrations.AddField(
            model_name='course',
            name='purchasers',
            field=models.ManyToManyField(blank=True, default=None, related_name='course_purchasers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_within_specialization', to='ecoles.specialization'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, related_name='course_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_note', to='ecoles.assignment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_note_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_within_submodule', to='ecoles.submodule'),
        ),
    ]
