# Generated by Django 4.0.6 on 2022-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='article_by_url',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='article_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Choose an assignment type', 'Choose an assignment type'), ('Text', 'Text'), ('Internal Link', 'Internal Link'), ('External Reading Link', 'External Reading Link'), ('External Link', 'External Link'), ('Iframe Link', 'Iframe Link'), ('Corsican Bible Chapter', 'Corsican Bible Chapter'), ('Youtube Video Link', 'Youtube Video Link'), ('Youtube Video Transcript ID', 'Youtube Video Transcript ID'), ('Article', 'Article')], default='Choose an assignment type', max_length=100),
        ),
    ]
