# Generated by Django 4.0.6 on 2022-08-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='corsican_bible_chapter',
        ),
    ]
