# Generated by Django 4.0.6 on 2022-07-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='url_keyword',
            field=models.CharField(default='', max_length=16),
        ),
    ]
