# Generated by Django 4.0.6 on 2022-08-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('ecoles', '0002_remove_assignment_corsican_bible_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='corsican_bible_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corsican_bible_chapter_assignment', to='languages.corsicanbiblechapter'),
        ),
    ]
