# Generated by Django 4.0.6 on 2022-08-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('General Skill', 'General Skill'), ('Foreign Language', 'Foreign Language'), ('Programming Language', 'Programming Language'), ('Programming Library or Framework', 'Programming Library or Framework'), ('Survival Skill', 'Survival Skill')], default='General Skill', max_length=64),
        ),
    ]
