# Generated by Django 4.0.6 on 2022-08-02 21:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoles', '0003_category_ecole_svg_url_alter_ecole_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Assignment', max_length=256)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('estimated_minutes_to_complete', models.FloatField(default=30)),
                ('assignment_type', models.CharField(choices=[('Choose an assignment type', 'Choose an assignment type'), ('Text', 'Text'), ('Internal Link', 'Internal Link'), ('External Reading Link', 'External Reading Link'), ('External Link', 'External Link'), ('Iframe Link', 'Iframe Link'), ('Corsican Bible Chapter', 'Corsican Bible Chapter'), ('Youtube Video Link', 'Youtube Video Link'), ('Youtube Video Transcript ID', 'Youtube Video Transcript ID')], default='Choose an assignment type', max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('internal_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('external_reading_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('external_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('iframe_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('youtube_video_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('youtube_video_transcript_id', models.CharField(blank=True, default='#', max_length=127, null=True)),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='assignment_completed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Module', max_length=64)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=100)),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='module_completed', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_within_course', to='ecoles.course')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('Read', 'Read'), ('Watch', 'Watch'), ('Notes', 'Notes'), ('Write', 'Write')], default='Read', max_length=15)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_within_assignment', to='ecoles.assignment')),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='task_completed', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Submodule', max_length=128)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='submodule_completed', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules_within_module', to='ecoles.module')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_note', to='ecoles.assignment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_note_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_within_submodule', to='ecoles.submodule'),
        ),
    ]
