# Generated by Django 4.0.6 on 2022-08-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_assignment_corsican_bible_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(blank=True, null=True, related_name='schools_that_course_belongs_to', to='ecoles.ecole'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='schools',
            field=models.ManyToManyField(blank=True, null=True, related_name='schools_that_specialization_belongs_to', to='ecoles.ecole'),
        ),
    ]
