# Generated by Django 4.0.6 on 2022-08-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0003_skill_skill_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
