# Generated by Django 4.0.6 on 2022-09-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0004_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentnote',
            name='visibility',
            field=models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='visibility',
            field=models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Private', max_length=100),
        ),
    ]
