# Generated by Django 4.0.6 on 2022-08-10 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoles', '0004_course_schools_specialization_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, related_name='ecole_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
