# Generated by Django 4.0.6 on 2022-08-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0004_alter_course_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations_within_field', to='ecoles.field'),
        ),
    ]
