# Generated by Django 4.0.6 on 2022-08-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0004_assignment_module_task_submodule_assignmentnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_within_field', to='ecoles.field'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specializations_within_field', to='ecoles.field'),
        ),
    ]
