# Generated by Django 4.0.6 on 2022-08-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0005_course_field_specialization_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='visibility',
        ),
    ]
