# Generated by Django 4.0.6 on 2022-08-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0007_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Choose an assignment type', 'Choose an assignment type'), ('Text', 'Text'), ('Internal Link', 'Internal Link'), ('External Reading Link', 'External Reading Link'), ('External Link', 'External Link'), ('Iframe Link', 'Iframe Link'), ('Youtube Video Link', 'Youtube Video Link'), ('Youtube Video Transcript ID', 'Youtube Video Transcript ID')], default='Choose an assignment type', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_within_assignment', to='ecoles.assignment'),
        ),
    ]
