# Generated by Django 4.0.6 on 2022-09-23 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoles', '0008_alter_course_price_alter_specialization_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchasers',
            field=models.ManyToManyField(blank=True, default=None, related_name='course_purchasers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='purchasers',
            field=models.ManyToManyField(blank=True, default=None, related_name='specialization_purchasers', to=settings.AUTH_USER_MODEL),
        ),
    ]
