# Generated by Django 4.0.6 on 2022-10-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecoles', '0009_course_purchasers_specialization_purchasers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_course', to='auth.group'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_specialization', to='auth.group'),
        ),
    ]
