# Generated by Django 4.0.6 on 2022-10-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoles', '0010_course_group_specialization_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
