# Generated by Django 4.0.6 on 2022-11-28 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=10000, unique=True)),
                ('source_name', models.CharField(max_length=10000, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('primary_language', models.CharField(default='en', max_length=10)),
                ('source_followers', models.ManyToManyField(blank=True, default=None, related_name='source_followers', to=settings.AUTH_USER_MODEL)),
                ('source_subscribers', models.ManyToManyField(blank=True, default=None, related_name='source_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceTwitterHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_twitter_handle', to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='SearchAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('article_by_url', models.BooleanField(default=True)),
                ('article_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesByTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('other_source', models.CharField(blank=True, default='', max_length=100)),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('google_url', models.CharField(default='', max_length=1023)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0)),
                ('article_by_url', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='Title', max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleByURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('title', models.CharField(default='-', max_length=255)),
                ('article_source', models.CharField(default='-', max_length=255)),
                ('page_title', models.CharField(default='-', max_length=255)),
                ('article_description', models.TextField(default='-')),
                ('domain_source', models.CharField(default='-', max_length=255)),
                ('domain_full', models.CharField(default='-', max_length=255)),
                ('text', models.TextField(default='-')),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('article_searched_by', models.CharField(default='url', max_length=15)),
                ('article_published_date', models.CharField(blank=True, max_length=255)),
                ('article_author', models.CharField(blank=True, max_length=255)),
                ('article_by_url_bookmarks', models.ManyToManyField(blank=True, default=None, related_name='article_by_url_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('article_by_url_flags', models.ManyToManyField(blank=True, default=None, related_name='article_by_url_flags', to=settings.AUTH_USER_MODEL)),
                ('article_by_url_stars', models.ManyToManyField(blank=True, default=None, related_name='article_by_url_stars', to=settings.AUTH_USER_MODEL)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleByTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('other_source', models.CharField(blank=True, default='', max_length=100)),
                ('URL', models.URLField(default='-')),
                ('title', models.CharField(default='-', max_length=255)),
                ('article_source', models.CharField(default='-', max_length=255)),
                ('page_title', models.CharField(default='-', max_length=255)),
                ('article_description', models.TextField(default='-')),
                ('domain_source', models.CharField(default='-', max_length=255)),
                ('domain_full', models.CharField(default='-', max_length=255)),
                ('text', models.TextField(default='-')),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('article_published_date', models.CharField(blank=True, max_length=255)),
                ('article_author', models.CharField(blank=True, max_length=255)),
                ('google_url', models.CharField(default='', max_length=1023)),
                ('article_searched_by', models.CharField(default='title', max_length=15)),
                ('article_by_title_bookmarks', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('article_by_title_flags', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_flags', to=settings.AUTH_USER_MODEL)),
                ('article_by_title_stars', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_stars', to=settings.AUTH_USER_MODEL)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.source')),
            ],
        ),
    ]
