# Generated by Django 4.0.6 on 2022-08-01 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=10000, unique=True)),
                ('source_name', models.CharField(max_length=10000, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('primary_language', models.CharField(default='en', max_length=10)),
                ('source_followers', models.ManyToManyField(blank=True, default=None, related_name='source_followers', to=settings.AUTH_USER_MODEL)),
                ('source_subscribers', models.ManyToManyField(blank=True, default=None, related_name='source_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SourceTwitterHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_twitter_handle', to='news.source')),
            ],
        ),
    ]
