# Generated by Django 4.0.6 on 2022-08-01 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleByURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('title', models.CharField(default='', max_length=255)),
                ('article_source', models.CharField(default='', max_length=255)),
                ('page_title', models.CharField(default='', max_length=255)),
                ('article_description', models.TextField(default='')),
                ('domain_source', models.CharField(default='', max_length=255)),
                ('domain_full', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('article_searched_by', models.CharField(default='url', max_length=15)),
                ('article_published_date', models.CharField(blank=True, max_length=255)),
                ('article_author', models.CharField(blank=True, max_length=255)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
