# Generated by Django 4.0.6 on 2022-08-01 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_articlebyurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlebyurl',
            name='article_by_url_bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_by_url_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlebyurl',
            name='article_by_url_flags',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_by_url_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlebyurl',
            name='article_by_url_stars',
            field=models.ManyToManyField(blank=True, default=None, related_name='article_by_url_stars', to=settings.AUTH_USER_MODEL),
        ),
    ]
