# Generated by Django 4.0.6 on 2022-08-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_articlebyurl_article_by_url_bookmarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0)),
                ('article_by_url', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='Title', max_length=128, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
