# Generated by Django 4.0.6 on 2022-08-01 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_articlenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesByTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('other_source', models.CharField(blank=True, default='', max_length=100)),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('google_url', models.CharField(default='', max_length=1023)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleByTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('other_source', models.CharField(blank=True, default='', max_length=100)),
                ('URL', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=255)),
                ('article_source', models.CharField(default='', max_length=255)),
                ('page_title', models.CharField(default='', max_length=255)),
                ('article_description', models.TextField(default='')),
                ('domain_source', models.CharField(default='', max_length=255)),
                ('domain_full', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('article_published_date', models.CharField(blank=True, max_length=255)),
                ('article_author', models.CharField(blank=True, max_length=255)),
                ('google_url', models.CharField(default='', max_length=1023)),
                ('article_searched_by', models.CharField(default='title', max_length=15)),
                ('article_by_title_bookmarks', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('article_by_title_flags', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_flags', to=settings.AUTH_USER_MODEL)),
                ('article_by_title_stars', models.ManyToManyField(blank=True, default=None, related_name='article_by_title_stars', to=settings.AUTH_USER_MODEL)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.source')),
            ],
        ),
    ]
