# Generated by Django 4.0.6 on 2022-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articlesbytitle_articlebytitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebytitle',
            name='URL',
            field=models.URLField(default='-'),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='article_description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='article_source',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='domain_full',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='domain_source',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='page_title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='text',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='articlebytitle',
            name='title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='article_description',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='article_source',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='domain_full',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='domain_source',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='page_title',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='text',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='articlebyurl',
            name='title',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
