# Generated by Django 4.0.6 on 2022-08-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reader',
            new_name='user',
        ),
    ]
