NUM_CREDITS_TO_ENTER_LOTTERY = 1
PAGINATE_BY = 50
LISTING_OBJ_TYPE = 'listing'
LISTING_FOR_GROUP_MEMBERS_OBJ_TYPE = 'listing_for_group_members'
AD_OFFER_OBJ_TYPE = 'ad_offer'
COURSE_OBJ_TYPE = 'course'
SPECIALIZATION_OBJ_TYPE = 'specialization'
COMMISSION_FEE = 0.006
STRIPE_PAYMENT_METHOD_TYPES = ["card"]
LOOKING_TO_BUY = "Bid (Looking to buy)"
LOOKING_TO_SELL = "Offer (Looking to sell)"
LOCAL_DOMAIN = "http://127.0.0.1:8000"
HOSTED_DOMAIN = "https://www.hoyabay.com"