# Generated by Django 4.0.6 on 2022-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twosidedfinancialtransaction',
            name='type_of_asset_received_by_entity_1',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Real Estate', 'Real Estate'), ('Stock', 'Stock'), ('Bond', 'Bond'), ('Physical Asset', 'Physical Asset'), ('Painting', 'Painting'), ('Arms', 'Arms'), ('Other', 'Other')], default='Cash', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='twosidedfinancialtransaction',
            name='type_of_asset_received_by_entity_2',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Real Estate', 'Real Estate'), ('Stock', 'Stock'), ('Bond', 'Bond'), ('Physical Asset', 'Physical Asset'), ('Painting', 'Painting'), ('Arms', 'Arms'), ('Other', 'Other')], default='Cash', max_length=64, null=True),
        ),
    ]
