# Generated by Django 4.0.6 on 2022-11-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('group_visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=64)),
                ('group_type', models.CharField(choices=[('Group', 'Group'), ('Club', 'Club'), ('Business', 'Business'), ('Nonprofit', 'Nonprofit'), ('Graduate School', 'Graduate School'), ('University', 'University'), ('High School', 'High School'), ('Middle School', 'Middle School'), ('Elementary School', 'Elementary School'), ('Other', 'Other')], default='Group', max_length=64)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('group_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_creator', to=settings.AUTH_USER_MODEL)),
                ('group_followers', models.ManyToManyField(blank=True, default=None, related_name='group_followers', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(blank=True, default=None, related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_requested', models.DateTimeField(auto_now_add=True)),
                ('group_receiving_membership_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_receiving_membership_request', to='auth.group')),
                ('user_requesting_to_become_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_to_become_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_requested', models.DateTimeField(auto_now_add=True)),
                ('group_receiving_follow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_receiving_follow_request', to='auth.group')),
                ('user_requesting_to_follow_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_to_follow_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
