# Generated by Django 4.0.6 on 2022-10-17 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='group_followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='group_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupFollowersCount',
        ),
    ]
