# Generated by Django 4.0.6 on 2022-11-10 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0002_paymenttogroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentToGroup',
            new_name='ListingForGroupMembers',
        ),
    ]
