# Generated by Django 4.0.6 on 2023-03-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_requestforpaymenttogroupmember_inserted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforpaymenttogroupmember',
            name='inserted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
