# Generated by Django 4.0.6 on 2022-11-10 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0003_rename_paymenttogroup_listingforgroupmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForPaymentToGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_for_group_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.listingforgroupmembers')),
                ('user_receiving_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
