# Generated by Django 4.0.6 on 2023-01-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_alter_suggesteddelivery_suggested_date_time'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpurchase',
            name='listing_to_be_advertised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_to_be_advertised', to='market.listing'),
        ),
    ]
