# Generated by Django 4.0.6 on 2022-10-24 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoffer',
            old_name='price_based_off_of',
            new_name='metric',
        ),
        migrations.AddField(
            model_name='adoffer',
            name='required_clicks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='adoffer',
            name='required_impressions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='adoffer',
            name='required_unique_impressions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
