# Generated by Django 4.0.6 on 2022-11-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpurchase',
            name='course_to_be_advertised',
        ),
        migrations.RemoveField(
            model_name='adpurchase',
            name='listing_to_be_advertised',
        ),
        migrations.RemoveField(
            model_name='adpurchase',
            name='post_to_be_advertised',
        ),
        migrations.RemoveField(
            model_name='adpurchase',
            name='specialization_to_be_advertised',
        ),
    ]
