# Generated by Django 4.0.6 on 2022-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_adpurchase_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpurchase',
            name='ad_type',
            field=models.CharField(choices=[('Specialization', 'Specialization'), ('Course', 'Course'), ('Post', 'Post'), ('Listing', 'Listing'), ('General Advertisement', 'General Advertisement')], default='General Advertisement', max_length=32),
        ),
    ]
