# Generated by Django 4.0.6 on 2022-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_price_based_off_of_adoffer_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoffer',
            name='title',
            field=models.CharField(default='Ad Offer', max_length=64, unique=True),
        ),
    ]
