# Generated by Django 4.0.6 on 2022-10-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_listing_quantity_available_and_more'),
        ('posts', '0002_post_group'),
        ('ecoles', '0011_alter_course_description_and_more'),
        ('ads', '0003_adpurchase_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpurchase',
            name='course_to_be_advertised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_to_be_advertised', to='ecoles.course'),
        ),
        migrations.AddField(
            model_name='adpurchase',
            name='general_advertisement_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adpurchase',
            name='listing_to_be_advertised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_to_be_advertised', to='market.listing'),
        ),
        migrations.AddField(
            model_name='adpurchase',
            name='post_to_be_advertised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_to_be_advertised', to='posts.post'),
        ),
        migrations.AddField(
            model_name='adpurchase',
            name='specialization_to_be_advertised',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization_to_be_advertised', to='ecoles.specialization'),
        ),
    ]
