# Generated by Django 4.0.6 on 2022-10-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_adoffer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoffer',
            name='description',
            field=models.TextField(default='Description for ad offer'),
        ),
    ]
