# Generated by Django 4.0.6 on 2022-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_adoffer_date_created_adpurchase_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoffer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adpurchase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
