# Generated by Django 4.0.6 on 2022-10-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ads', '0006_alter_adoffer_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpurchase',
            name='group_that_purchased_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_purchased_ad', to='auth.group'),
        ),
    ]
