# Generated by Django 4.0.6 on 2022-11-11 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_obj_type', models.CharField(max_length=128)),
                ('transaction_obj_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=128)),
                ('seller_verified', models.BooleanField(blank=True, null=True)),
                ('purchaser_verified', models.BooleanField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('end_payment_sent', models.BooleanField(default=False)),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Listing', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('Invisible', 'Invisible'), ('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Anonymous', max_length=100)),
                ('listing_type', models.CharField(choices=[('Offer', 'Offer'), ('Request', 'Request')], default='Request', max_length=100)),
                ('listing_category', models.CharField(choices=[('General', 'General'), ('Consulting', 'Consulting'), ('Tutoring', 'Tutoring'), ('Sale', 'Sale')], default='General', max_length=100)),
                ('listing_medium', models.CharField(choices=[('Digital File(s)', 'Digital File(s)'), ('In-Person Service', 'In-Person Service'), ('Digital Service', 'Digital Service'), ('Physical Product', 'Physical Product')], default='General', max_length=100)),
                ('infinite_copies_available', models.BooleanField(default=True)),
                ('quantity_available', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_that_created_listing', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_listing', to='auth.group')),
                ('purchasers', models.ManyToManyField(blank=True, default=None, related_name='purchasers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fundraiser', max_length=64)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=25)),
                ('funds_needed', models.IntegerField(default=25)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_that_created_fundraiser', to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_that_created_fundraiser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
