# Generated by Django 4.0.6 on 2022-09-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='offer',
            new_name='request_for_help',
        ),
    ]
