# Generated by Django 4.0.6 on 2022-10-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Offer', 'Offer'), ('Request', 'Request')], default='Request', max_length=100),
        ),
    ]
