# Generated by Django 4.0.6 on 2023-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Public', max_length=100),
        ),
    ]
