# Generated by Django 4.0.6 on 2022-10-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_listing_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='non_fungible_order',
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
