# Generated by Django 4.0.6 on 2023-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_listing_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='infinite_copies_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('Offer (Looking to sell)', 'Offer (Looking to sell)'), ('Bid (Looking to buy)', 'Bid (Looking to buy)')], default='Offer (Looking to sell)', max_length=100),
        ),
    ]
