# Generated by Django 4.0.6 on 2022-09-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_transaction_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='item_title',
            new_name='title',
        ),
    ]
