# Generated by Django 4.0.6 on 2022-10-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_listing_non_fungible_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='infinite_copies_available',
            field=models.BooleanField(default=True),
        ),
    ]
