# Generated by Django 4.0.6 on 2023-01-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_listing_infinite_copies_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_due',
        ),
    ]
