# Generated by Django 4.0.6 on 2022-09-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_listing_listing_type_alter_listing_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='request_for_help',
        ),
    ]
