# Generated by Django 4.0.6 on 2022-10-23 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_listing_infinite_copies_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purchasers',
            field=models.ManyToManyField(blank=True, default=None, related_name='purchasers', to=settings.AUTH_USER_MODEL),
        ),
    ]
