# Generated by Django 4.0.6 on 2022-09-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_listing_request_for_help'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='creator',
        ),
    ]
