# Generated by Django 4.0.6 on 2022-10-23 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_listing_purchasers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity_available',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_sold',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
