# Generated by Django 4.0.6 on 2022-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_listing_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('General', 'General'), ('Consulting', 'Consulting'), ('Tutoring', 'Tutoring'), ('Sale', 'Sale')], default='General', max_length=100),
        ),
    ]
