# Generated by Django 4.0.6 on 2023-01-12 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0006_alter_listing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('georgetown_location', models.CharField(blank=True, choices=[('Copley', 'Copley'), ('Darnall', 'Darnall'), ('Harbin', 'Harbin'), ('New South', 'New South'), ('Arrupe', 'Arrupe'), ('Village B', 'Village B'), ('Village A', 'Village A'), ('Henle', 'Henle'), ('LXR', 'Lxr'), ('Kennedy', 'Kennedy'), ('McCarthy', 'Mccarthy'), ('Reynolds', 'Reynolds'), ('Nevils', 'Nevils'), ('Village C', 'Village C'), ('Townhouse', 'Townhouse'), ('Off Campus', 'Off Campus'), ("Leo's", 'Leos'), ('Healy Hall', 'Healy Hall'), ('HSFC', 'Hsfc'), ('Lauinger Library', 'Lau'), ('White-Gravenor', 'White Gravenor'), ('ICC', 'Icc'), ('Leavey Center', 'Leavey Center'), ('Yates', 'Yates'), ('None', 'None')], default='None', max_length=100, null=True)),
                ('suggested_time', models.DateTimeField()),
                ('seller_verified', models.BooleanField(blank=True, null=True)),
                ('purchaser_verified', models.BooleanField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='market.listing')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser_of_listing', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_of_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='market.suggesteddelivery'),
        ),
    ]
