# Generated by Django 4.0.6 on 2022-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='non_fungible_order',
            field=models.BooleanField(default=True),
        ),
    ]
