# Generated by Django 4.0.6 on 2023-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_suggesteddelivery_transaction_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=100),
        ),
    ]
