# Generated by Django 4.0.6 on 2023-01-13 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0008_alter_listing_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lottery Prize', max_length=128)),
                ('lottery_ends_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='market.listing'),
        ),
        migrations.CreateModel(
            name='PaymentIntentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=264, unique=True)),
                ('stripe_account_id', models.CharField(max_length=264)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_lottery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_lottery', to=settings.AUTH_USER_MODEL)),
                ('lottery_participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lottery_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentintenttracker',
            constraint=models.UniqueConstraint(fields=('stripe_account_id', 'listing', 'user'), name='unique_payment_intent'),
        ),
    ]
