# Generated by Django 4.0.6 on 2022-09-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_listing_non_fungible_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_obj_type_id',
            new_name='transaction_obj_id',
        ),
    ]
