# Generated by Django 4.0.6 on 2023-01-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_lottery_alter_suggesteddelivery_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddelivery',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
