# Generated by Django 4.0.6 on 2023-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_suggesteddelivery_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
