# Generated by Django 4.0.6 on 2023-01-13 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddelivery',
            name='suggested_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 18, 7, 10, 891735)),
        ),
    ]
