# Generated by Django 4.0.6 on 2023-01-13 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_suggesteddelivery_suggested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 13, 23, 8, 34, 424644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 23, 8, 34, 424827, tzinfo=utc)),
        ),
    ]
