# Generated by Django 4.0.6 on 2023-01-13 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_suggesteddelivery_suggested_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggesteddelivery',
            name='suggested_date',
        ),
        migrations.RemoveField(
            model_name='suggesteddelivery',
            name='suggested_time',
        ),
        migrations.AddField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 23, 9, 12, 129411, tzinfo=utc)),
        ),
    ]
