# Generated by Django 4.0.6 on 2023-01-14 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_suggesteddelivery_suggested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddelivery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 52, 14, 726783, tzinfo=utc)),
        ),
    ]
