# Generated by Django 4.0.6 on 2023-01-14 01:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_suggesteddelivery_georgetown_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 1, 4, 22, 902634, tzinfo=utc)),
        ),
    ]
