# Generated by Django 4.0.6 on 2023-01-14 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_suggesteddelivery_suggested_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggesteddelivery',
            name='created_by',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 2, 24, 1, 220719, tzinfo=utc)),
        ),
    ]
