# Generated by Django 4.0.6 on 2023-01-14 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_listing_map_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='map_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 1, 3, 4661, tzinfo=utc)),
        ),
    ]
