# Generated by Django 4.0.6 on 2023-01-14 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_alter_suggesteddelivery_suggested_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='title',
            new_name='prize',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='lottery_ends_on',
        ),
        migrations.AddField(
            model_name='lottery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='lotteries/images'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='num_unique_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lottery',
            name='num_unique_users_required',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 22, 30, 34, 317512, tzinfo=utc)),
        ),
    ]
