# Generated by Django 4.0.6 on 2023-01-14 23:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0029_lottery_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lottery_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 23, 44, 42, 347482, tzinfo=utc)),
        ),
    ]
