# Generated by Django 4.0.6 on 2023-01-15 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_alter_lottery_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 15, 26, 51, 335186, tzinfo=utc)),
        ),
    ]
