# Generated by Django 4.0.6 on 2023-01-29 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, default='/Users/braedenlevine/Dropbox/Mac/Desktop/malagosto/media/hoyabay/images/sailboat.png', null=True, upload_to='listings/images'),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 16, 37, 36, 436353, tzinfo=utc)),
        ),
    ]
