# Generated by Django 4.0.6 on 2023-02-01 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0048_alter_suggesteddelivery_suggested_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Anonymous', 'Anonymous')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 21, 41, 42, 791668, tzinfo=utc)),
        ),
    ]
