# Generated by Django 4.0.6 on 2023-02-04 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0051_alter_listing_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 2, 9, 34, 957893, tzinfo=utc)),
        ),
    ]
