# Generated by Django 4.0.6 on 2023-02-24 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_rename_listing_for_group_members_type_listingforgroupmembers_listing_type'),
        ('market', '0058_alter_suggesteddelivery_suggested_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintenttracker',
            name='listing_for_group_members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orgs.listingforgroupmembers'),
        ),
        migrations.AlterField(
            model_name='paymentintenttracker',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.listing'),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 17, 36, 36, 870157, tzinfo=utc)),
        ),
    ]
