# Generated by Django 4.0.6 on 2023-03-18 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0059_paymentintenttracker_listing_for_group_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggesteddelivery',
            old_name='georgetown_location',
            new_name='deliveryLocation',
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Listing', max_length=128),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 6, 47, 263041, tzinfo=utc)),
        ),
    ]
