# Generated by Django 4.0.6 on 2023-03-18 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0060_rename_georgetown_location_suggesteddelivery_deliverylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('Brand new (5/5)', 'Brand new (5/5)'), ('Practically new (4/5)', 'Practically new (4/5)'), ('Used but in good condition (3/5)', 'Used but in good condition (3/5)'), ('Used and in ok condition (2/5)', 'Used and in ok condition (2/5)'), ('Poor condition (1/5)', 'Poor condition (1/5)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 10, 35, 13, 28064, tzinfo=utc)),
        ),
    ]
