# Generated by Django 4.0.6 on 2023-03-18 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0063_alter_listing_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddelivery',
            name='suggested_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
