# Generated by Django 4.0.6 on 2023-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0065_alter_transaction_purchaser_alter_transaction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('Tutoring - Arts & Humanities', 'Tutoring - Arts & Humanities'), ('Tutoring - Sciences', 'Tutoring - Sciences'), ('Tutoring - Programming & Technology', 'Tutoring - Programming & Technology'), ('Tutoring - Business', 'Tutoring - Business'), ('Tutoring - Other', 'Tutoring - Other'), ('Notes - Arts & Humanities', 'Notes - Arts & Humanities'), ('Notes - Sciences', 'Notes - Sciences'), ('Notes - Programming & Technology', 'Notes - Programming & Technology'), ('Notes - Business', 'Notes - Business'), ('Notes - Other', 'Notes - Other'), ('Consulting services', 'Consulting services'), ('Translation services', 'Translation services'), ('Programming services', 'Programming services'), ('Research assistance', 'Research assistance'), ('Interview prep', 'Interview prep'), ('Résumé help', 'Résumé help'), ('Other services', 'Other services'), ('Book', 'Book'), ('Textbook', 'Textbook'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Household', 'Household'), ('Sports tickets', 'Sports tickets'), ('Concert tickets', 'Concert tickets'), ('Local event tickets', 'Local event tickets'), ('Other tickets', 'Other tickets'), ("Men's basketball sneakers", "Men's basketball sneakers"), ("Women's basketball sneakers", "Women's basketball sneakers"), ("Men's running sneakers", "Men's running sneakers"), ("Women's running sneakers", "Women's running sneakers"), ("Men's casual sneakers", "Men's casual sneakers"), ("Women's casual sneakers", "Women's casual sneakers"), ("Men's formal wear", "Men's formal wear"), ("Women's formal wear", "Women's formal wear"), ("Other men's shoes", "Other men's shoes"), ("Other women's shoes", "Other women's shoes"), ("Men's jackets", "Men's jackets"), ("Women's jackets", "Women's jackets"), ("Men's sweatshirts", "Men's sweatshirts"), ("Women's sweatshirts", "Women's sweatshirts"), ("Men's formal wear", "Men's formal wear"), ("Women's formal wear", "Women's formal wear"), ("Men's clothing - Other", "Men's clothing - Other"), ("Women's clothing - Other", "Women's clothing - Other"), ("Men's suits", "Men's suits"), ("Women's dresses", "Women's dresses"), ('Gift cards', 'Gift cards'), ('Other', 'Other')], default='Book', max_length=100),
        ),
    ]
