# Generated by Django 4.0.6 on 2023-03-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0067_alter_transaction_purchaser_alter_transaction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='hoyabay/tickets/digital'),
        ),
    ]
