# Generated by Django 4.0.6 on 2023-03-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0068_listing_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForDigitalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.transaction')),
                ('user_receiving_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_request_and_thus_sending_ticket', to=settings.AUTH_USER_MODEL)),
                ('user_sending_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending_request_and_thus_receiving_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
