# Generated by Django 4.0.6 on 2023-03-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0069_requestfordigitalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='requestfordigitalticket',
            name='user_receiving_request',
        ),
        migrations.RemoveField(
            model_name='requestfordigitalticket',
            name='user_sending_request',
        ),
        migrations.AddField(
            model_name='requestfordigitalticket',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='hoyabay/tickets/digital'),
        ),
    ]
