# Generated by Django 4.0.6 on 2023-03-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0071_remove_requestfordigitalticket_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='hoyabay/tickets/digital'),
        ),
    ]
