# Generated by Django 4.0.6 on 2022-11-11 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_group_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_group_profile', to='orgs.groupprofile'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_members',
            field=models.ManyToManyField(blank=True, default=None, related_name='room_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='receiver_of_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_of_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_of_message', to='messaging.room'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sender_of_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_of_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
