# Generated by Django 4.0.6 on 2023-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hoyabay/messaging/files'),
        ),
    ]
