# Generated by Django 4.0.6 on 2022-10-27 11:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='DirectMessage',
        ),
    ]
