# Generated by Django 4.0.6 on 2022-10-27 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_rename_message_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='date_time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
