# Generated by Django 4.0.6 on 2022-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_directmessage_date_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='date_time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
