# Generated by Django 4.0.6 on 2022-11-03 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0007_room_alter_directmessage_receiver_of_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_members',
            field=models.ManyToManyField(blank=True, default=None, related_name='room_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
