# Generated by Django 4.0.6 on 2022-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_room_room_creator_room_room_group_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
