# Generated by Django 4.0.6 on 2022-11-04 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0010_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='membership_requesters',
            field=models.ManyToManyField(blank=True, default=None, related_name='membership_requesters', to=settings.AUTH_USER_MODEL),
        ),
    ]
