# Generated by Django 4.0.6 on 2022-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_result_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficluty',
            new_name='difficulty',
        ),
    ]
