# Generated by Django 4.0.6 on 2022-08-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0004_rename_difficluty_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='article_by_url',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='article_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
